eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5436/order_db}
    username: postgres
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      Object → JSON bytes.
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      acks: all
      properties:
        delivery.timeout.ms: 30000 # Tổng thời gian tối đa để retry và gửi tin nhắn
        request.timeout.ms: 15000  # Thời gian chờ phản hồi cho từng request đơn lẻ
        linger.ms: 0               # Gửi ngay lập tức, không gom batch
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
        #3 cái bị lỗi thì chuyển half open
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:

      backendA:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicatior: true

      backendB:
        limitForPeriod: 6
        limitRefreshPeriod: 500ms
        timeoutDuration: 3s
jpa:
  show-sql: true
server:
  port: 8089