services:

  postgres:
    image: postgis/postgis:18-3.6
    container_name: order-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db

    ports:
      - "5436:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    networks:
      ecommerce-shared:



  redis:
    image: redis:7.0-alpine
    container_name: mpm-handover-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      ecommerce-shared:
  # UI để quản lý Redis
  redis-insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight-ui
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
    networks:
      ecommerce-shared:

  zookeeper:
    container_name: mpm-handover-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      ecommerce-shared:
  kafka:
    container_name: mpm-handover-kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://127.0.0.1:9092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ecommerce-shared:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-mpm-handover-10
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      ecommerce-shared:
  vti-keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: vti-keycloak

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

    command: start-dev

    ports:
      - "8180:8080"

    depends_on:
      - postgres
    networks:
      ecommerce-shared:
#    networks:
#      - default
  elasticsearch:
    container_name: vti-elasticsearch
    image: elasticsearch:7.17.10
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      ecommerce-shared:
#    networks:
#      - default

  logstash:
    container_name: vti-logstash
    image: logstash:7.17.10
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
#    networks:
#      - default
    depends_on:
      - elasticsearch
    networks:
      ecommerce-shared:

  kibana:
    container_name: kb-container
    image: kibana:7.17.10
    environment:
      ELASTICSEARCH_HOSTS: http://vti-elasticsearch:9200
#    networks:
#      - optimize-network
#    depends_on:
#      - default
    ports:
      - "5601:5601"
    networks:
      ecommerce-shared:
  connect:
    image: quay.io/debezium/connect:3.6
    container_name: order-debezium-connect
    restart: unless-stopped

    ports:
      - "8083:8083"

    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: order-connect-group

      CONFIG_STORAGE_TOPIC: order_connect_configs
      OFFSET_STORAGE_TOPIC: order_connect_offsets
      STATUS_STORAGE_TOPIC: order_connect_statuses

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

    depends_on:
      - kafka
      - postgres
    networks:
      ecommerce-shared:
#    networks:
#      - default
volumes:
  product_postgres_data:
  zookeeper-data:
  kafka-data:
  redis-data:
  redis-insight-data:

networks:
  ecommerce-shared:
    external: true
#    driver: bridge
#
#  keycloak-network:
#    driver: bridge
#
#  optimize-network:
#    driver: bridge

