eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5435/product_db}
    username: postgres
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
#      JSON bytes → chuỗi JSON.
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.springframework.cache: trace
    com.github.benmanes.caffeine: debug
    org.springframework.data.redis: debug
jpa:
  show-sql: true
server:
  port: 8088




