services:

  postgres:
    image: postgis/postgis:18-3.6
    container_name: product-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db

    ports:
      - "5435:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql

#  redis:
#    image: redis:7.0-alpine
#    container_name: mpm-handover-redis
#    ports:
#      - "6380:6379"
#    volumes:
#      - redis-data:/data
#    command: redis-server --appendonly yes
#  # UI để quản lý Redis
#  redis-insight:
#    image: redislabs/redisinsight:1.14.0
#    container_name: redis-insight-ui
#    ports:
#      - "8002:8001"
#    volumes:
#      - redis-insight-data:/data
#    depends_on:
#      - redis
#
#  zookeeper:
#    container_name: mpm-handover-zookeeper
#    image: wurstmeister/zookeeper
#    ports:
#      - 2182:2181
#
#  kafka:
#    container_name: mpm-handover-kafka
#    image: wurstmeister/kafka
#    ports:
#      - 9093:9092
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://127.0.0.1:9093
#      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#    depends_on:
#      - zookeeper
#    volumes:
#      - kafka-data:/kafka
#      - /var/run/docker.sock:/var/run/docker.sock
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui-mpm-handover-10
#    ports:
#      - "8082:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181




volumes:
  product_postgres_data:
#  zookeeper-data:
#  kafka-data:
#  redis-data:
#  redis-insight-data: