services:

  postgres:
    image: postgis/postgis:18-3.6
    container_name: product-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db

    ports:
      - "5435:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql


volumes:
  product_postgres_data: